### PR TITLE
* export '_bump' textures when model saved as FBX

### PR DESCRIPTION
**Pull request by SkyLoaderr**
* changed cursor type during export

### CODE REVIEW

**Comment by iOrange** [comment]
Thanks for the pull-request, but I've finally implemented surface gather and export functionality in MetroEX  (I'll need it for better models and levels rendering anyway).

**Comment by SkyLoaderr** [comment]
Ok. What about second commit "+ added ability to save only current animation"?

**Comment by iOrange** [comment]
Hmm, seems like I've overlooked that.
Sorry, will integrate.

**Comment by iOrange** [comment]
Integrated your changes into the main branch. Commit e90ff4c96b5042692f0b75a37d14b7628f8b11e6

**Pull request closed without merging**
